### GET application of unreal wilders in JSON format
GET  https://http-practice.herokuapp.com/wilders


### GET application of unreal wilders in JSON format (with query string)
GET  https://http-practice.herokuapp.com/wilders/?language=JavaScript&page=2


##############################################################################"
##############################################################################"

### POST application of unreal wilders in standard format
POST https://http-practice.herokuapp.com/wilders
Content-Type: application/x-www-form-urlencoded

name=John%20Doe&language=CSharp

### POST application of unreal wilders in JSON format
POST https://http-practice.herokuapp.com/wilders
Content-Type: application/json

{
  "id": 1646519,
  "name": "Will Iam",
  "language": "PHP"
}

##############################################################################"
##############################################################################"

### PUT application of unreal wilders in JSON format
PUT https://http-practice.herokuapp.com/wilders/1646519
Content-Type: application/json

{
  "name": "WillIam",
  "language": "PHP"
}

##############################################################################"
##############################################################################"

### DELETE application of unreal wilders in JSON format
DELETE https://http-practice.herokuapp.com/wilders/1645102



